### PR TITLE
fix(package): fixed `engine` warning

### LINKED ISSUE #105: engine warning
While installing dependencies on a repo that uses this package, I noticed this:
```shell
warning name-your-contributors@3.8.2: The engine "nodejs" appears to be invalid
```
Which makes sense since the engine name is simply `"node"`.

### PR DESCRIPTION
**Pull request by Berkmann18**
fix #105

### CODE REVIEW

**Comment by Berkmann18** [comment]
@RichardLitt Do you also get the [EOTP error](https://travis-ci.org/mntnr/name-your-contributors/jobs/535191452) when TravisCI is on the release stage or is just me?

**Comment by RichardLitt** [comment]
You mean this error? https://travis-ci.org/mntnr/name-your-contributors/jobs/535191452

**Comment by Berkmann18** [comment]
Yeah, the one starting at line 577.

**Comment by RichardLitt** [comment]
Looks like an issue with publishing. I don't know why travis needs to publish, though - something to do with semantic release, I suppose? @gr2m might know.

**Comment by Berkmann18** [comment]
@RichardLitt It's because `semantic-release` needs a token to publish to NPM as part of the CI workflow.

**Comment by gr2m** [comment]
Here is the problem

```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```

The account requires 2-factor authentication, this won’t work with semantic-release. What I recommend to do is to create a dedicated npm account, invite it as collaborator to the name-your-contributors package, make sure it does not have 2FA enabled, then create a token with that account and store it on travis

**Comment by Berkmann18** [comment]
@gr2m It's maybe because I use 2FA while being a collaborator of this repo.

**Comment by gr2m** [comment]
It only matters which account was used when semantic-release was setup

**Comment by Berkmann18** [comment]
@gr2m Really? Surely, the account pushing the changes that are going through the CI are going to influence the use of 2FA, no?

**Comment by gr2m** [comment]
no, semantic-release doesn’t care who pushed changes where. It’s running in a git-enabled folder and publishes what ever is in there. I use separate npm accounts for semantic-release all the time. Many people who push the changes have 2FA enabled

**Comment by Berkmann18** [comment]
Fair enough.

**Pull request merged**
