### PR TITLE
fix(package-lock): fixed some vulnerabilities

### PR DESCRIPTION
**Pull request by Berkmann18**
While updating the package-lock, NPM logged 19 vulnerabilities and I fixed all of them.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Doesn't this also have to involve updating the package.json?

**Comment by Berkmann18** [comment]
@RichardLitt Not always as sometimes NPM (technically NSP) and even Snyk will update only dependencies at a certain depth while keeping the same direct dependencies.

**Comment by Berkmann18** [comment]
@RichardLitt Not always as sometimes NPM (technically NSP) and even Snyk will update only dependencies at a certain depth while keeping the same direct dependencies.

**Comment by RichardLitt** [comment]
Good to know! Can you rebase? I'm not sure how you solved this, so I don't think doing a line-by-line diff rebase on my end would work.

**Comment by Berkmann18** [comment]
I just noticed my travis PR may have broken the `npm ci` bit in the build and I'm not sure if it's one of those random NPM failures that I see once in a while or if the `greenkeeper-lockfile` script has something to do with it.

**Comment by RichardLitt** [comment]
Let's find out. Thank you.

**Pull request merged**
